namespace Runtime.WorkInProgress
{
    public enum TraitTag
    {
        Fire,
        Lightning,
        Cold,
        Physical,
        Poison,
        AoE,
        Attack,
        Spell,
        Trigger,
        Cast,
        Melee,
        Ranged,
        Projectile,
        Movement,
        Speed,
        Life,
        Mana,
        Strength,
        Dexterity,
        Intelligence,
        Attunement,
        Malevolence,
        Faith,
        GoldFind,
        ItemFind,
        Experience,
        RegenerationFlat,
        RegenerationPercent,
        Recovery,
        HealthGlobeFlat,
        HealthGlobePercent
    }
}