namespace Runtime.WorkInProgress
{
    public enum TraitTag
    {
        Fire = 0,
        Lightning = 1,
        Cold = 2,
        Physical = 3,
        Poison = 4,
        AoE = 5,
        Attack = 6,
        Spell = 7,
        Trigger = 8,
        Cast = 9,
        Melee = 10,
        Ranged = 11,
        Projectile = 12,
        Movement = 13,
        Speed = 14,
        Life = 15,
        Mana = 16,
        Strength = 17,
        Dexterity = 18,
        Intelligence = 19,
        Attunement = 20,
        Malevolence = 21,
        Faith = 22,
        GoldFind = 23,
        ItemFind = 24,
        Experience = 25,
        RegenerationFlat = 26,
        RegenerationPercent = 27,
        Recovery = 28,
        HealthGlobeFlat = 29,
        HealthGlobePercent = 30,
        EnergyShield = 31,
        Potion = 32,
        Damage = 33,
        Radius = 34,
    }
}